### ISSUE TITLE
Employee Filter

### ISSUE THREAD

**Issue by eunizorozco** [kasclem/ReactJS_GitTut#3]
STORY
--------
I want to search all employees by employee id, name, position and department
so that I can filter all employees in the list

ACCEPTANCE CRITERIA
------------------------
GIVEN i have an employee id <1565>
WHEN I enter an employee id to the field
AND I press the search button
THEN I must see the employee in the list that has that employee id

**Comment by LeandroAmores** [comment]
goodjob

**Comment by LeandroAmores** [comment]
goodjob
